services:
  - type: web
    name: my-car-value
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: my-car-value-db
          property: connectionString
      - key: COOKIE_KEY
        generateValue: true

databases:
  - name: my-car-value-db
    plan: free
    ipAllowList: []